
#!name=CapCut + TikTok Unlock
#!desc=Unlock CapCut Premium & Block TikTok tracking
#!author=ng-anhtuan + Chat GPT
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png

[MITM]
hostname = %APPEND%, api.revenuecat.com, api2.musical.ly, log.tiktokv.com

[Script]
capcut = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers\/[^/]+$, requires-body=true, script-path=https://raw.githubusercontent.com/ng-anhtuan/shadowrocket-modules/refs/heads/main/js/capcut/capcut.js, timeout=60
tiktok = type=http-request, pattern=^https:\/\/api2\.musical\.ly\/.+(log|track|monitor), requires-body=false, script-path=https://github.com/ng-anhtuan/shadowrocket-modules/blob/main/js/tiktok/blockTracking.js, timeout=30

[Rule]
DOMAIN-SUFFIX,capcut.com,PROXY
DOMAIN-KEYWORD,tiktok,PROXY
DOMAIN-KEYWORD,ads,REJECT
DOMAIN-KEYWORD,tracking,REJECT
DOMAIN-KEYWORD,analytics,REJECT
