#!name=CapCut Premium Unlocker
#!desc=Unlock CapCut Premium (Pro) via Shadowrocket Rewrite + Script
#!author=ng-anhtuan
#!homepage=https://github.com/ng-anhtuan/shadowrocket-modules
#!icon=https://raw.githubusercontent.com/ng-anhtuan/shadowrocket-modules/main/icon/capcut.png
#!version=1.0.0

[MITM]
hostname = api2.mojocode.ai

[Script]
capcut-premium.js = type=http-response,pattern=^https:\/\/api2\.mojocode\.ai\/.+\/subscription\/status,requires-body=true,max-size=0,script-path=https://raw.githubusercontent.com/ng-anhtuan/shadowrocket-modules/refs/heads/main/capcut-premium.js
